# Site settings
title: Testing Jekyll
email: hello-jekyll@mailinator.com
description: > # this means to ignore newlines until "baseurl:"
  Playground to discover Jekyll's magic
baseurl: "/hello-jekyll" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
timezone: Asia/Kolkata

# Build settings
markdown: kramdown
# kramdown:
#   input: GFM
